import {
  plugins as airbnbPlugins,
  configs as airbnb,
} from "eslint-config-airbnb-extended";
import prettier from "eslint-config-prettier";
import checkFile from "eslint-plugin-check-file";
import jsdoc from "eslint-plugin-jsdoc";
import lit from "eslint-plugin-lit";
import litA11y from "eslint-plugin-lit-a11y";
import wc from "eslint-plugin-wc";
import { defineConfig, globalIgnores } from "eslint/config";
import globals from "globals";

const jsdocRules = {
  // Require a JSDoc block on the public surface — exported functions/classes and
  // public (non-`_`) methods incl. the HA card-contract statics. Private `_`
  // helpers and inline arrows stay documented by their `//` WHY-comments.
  "jsdoc/require-jsdoc": [
    "error",
    {
      require: {
        FunctionDeclaration: false,
        ArrowFunctionExpression: false,
        FunctionExpression: false,
        ClassDeclaration: false,
        MethodDefinition: false,
      },
      contexts: [
        "ExportNamedDeclaration > FunctionDeclaration",
        "ExportNamedDeclaration > VariableDeclaration > VariableDeclarator > ArrowFunctionExpression",
        "ExportNamedDeclaration > ClassDeclaration",
        "MethodDefinition[key.name!=/^_/]",
      ],
      checkConstructors: false,
    },
  ],
  "jsdoc/require-description": "error",
};

export default defineConfig([
  globalIgnores([
    "dist/**",
    "node_modules/**",
    "src/generated/icons.core.gen.js", // generated by scripts/gen-icons.mjs
    "src/generated/tailwind.gen.js", // generated by scripts/gen-tw.mjs
    "storybook/storybook-static/**",
    "storybook/node_modules/**",
    "bun.lock",
  ]),

  // --- Airbnb styleguide. Plugins must register before the rule sets that use
  // them; the presets self-scope via their own globs and keep type-checked rules
  // off plain JS.
  airbnbPlugins.stylistic,
  airbnbPlugins.importX,
  airbnbPlugins.node,
  airbnbPlugins.typescriptEslint,
  ...airbnb.base.recommended,
  ...airbnb.base.typescript,

  // --- src/** : Lit + web-component + a11y layer on top of Airbnb ---
  {
    files: ["src/**/*.{js,ts}"],
    extends: [lit.configs["flat/recommended"], wc.configs["flat/recommended"]],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...globals.browser },
    },
    plugins: { jsdoc, "lit-a11y": litA11y, "check-file": checkFile },
    rules: {
      ...litA11y.configs.recommended.rules,
      ...jsdocRules,
      "check-file/filename-naming-convention": [
        "error",
        { "**/*.{js,ts}": "KEBAB_CASE" },
        { ignoreMiddleExtensions: true },
      ],
    },
  },

  // --- Repo/Lit conventions that intentionally diverge from stock Airbnb ---
  {
    files: ["src/**/*.{js,ts}"],
    rules: {
      "no-underscore-dangle": "off", // private `_method`/`_state` convention
      "class-methods-use-this": "off", // Lit render()/lifecycle needn't use `this`
      "import-x/extensions": "off", // bundler + @ aliases resolve extensions
      "import-x/no-unresolved": "off", // @shared/@core/@cards aliases
      "import-x/prefer-default-export": "off", // named card exports are the norm
      "no-plusplus": "off",
      "no-restricted-syntax": "off",
      "no-continue": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },

  // --- build scripts + Vite/ESLint config : Node ---
  {
    files: ["scripts/**/*.mjs", "eslint.config.js", "vite.config.ts"],
    languageOptions: { globals: { ...globals.node } },
    rules: {
      "import-x/no-extraneous-dependencies": "off",
      "import-x/extensions": "off", // Node ESM build scripts use explicit .js
      "no-console": "off",
      "no-continue": "off",
      "no-shadow": "off",
      "no-restricted-syntax": "off", // for..of over Rollup's bundle map is fine here
      "no-param-reassign": "off", // Rollup's generateBundle mutates chunk.code
    },
  },

  // --- storybook : a separate showcase package (own package.json/build).
  // Lint lightly — relax the product-grade Airbnb rules that don't suit the
  // config-driven story/fixture files. ---
  {
    files: ["storybook/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      "import-x/no-extraneous-dependencies": "off",
      "import-x/extensions": "off", // native ESM in Storybook's own Vite
      // Separate package — its node_modules isn't installed when the root lints
      // (CI runs only the root `bun install`); the storybook job builds it for real.
      "import-x/no-unresolved": "off",
      "import-x/no-relative-packages": "off",
      "import-x/first": "off",
      "no-console": "off",
      "no-underscore-dangle": "off",
      "no-param-reassign": "off",
      "no-return-assign": "off",
      "no-restricted-syntax": "off",
      "no-restricted-globals": "off",
      "prefer-template": "off",
      "func-names": "off",
      "@stylistic/lines-between-class-members": "off",
    },
  },

  // Disables stylistic rules that would fight Prettier — must stay last.
  prettier,
]);
