import js from "@eslint/js";
import globals from "globals";
import importPlugin from "eslint-plugin-import";
import checkFile from "eslint-plugin-check-file";
import lit from "eslint-plugin-lit";
import wc from "eslint-plugin-wc";
import jsdoc from "eslint-plugin-jsdoc";
import prettier from "eslint-config-prettier";
import { defineConfig, globalIgnores } from "eslint/config";

// Airbnb best-practices applied as an explicit, curated set (not `extends:
// airbnb-base`) so the ruleset stays legible and matched to this repo — the same
// approach used in the Athena frontend's eslint.config.js.
const airbnb = {
  "no-var": "error",
  "prefer-const": "error",
  // A local shadowing an import (`const t = …` over the i18n `t`) is a silent
  // data-loss class of bug (see alert.js backup_age); make it an error.
  "no-shadow": ["error", { builtinGlobals: false }],
  "object-shorthand": ["warn", "always"],
  "prefer-template": "warn",
  "no-else-return": ["warn", { allowElseIf: false }],
  eqeqeq: ["error", "always", { null: "ignore" }],
  "no-unused-vars": [
    "warn",
    {
      argsIgnorePattern: "^_",
      varsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
    },
  ],
};

export default defineConfig([
  globalIgnores([
    "dist/**",
    "node_modules/**",
    "src/generated/icons.core.gen.js", // generated by scripts/gen-icons.mjs
    "src/generated/tailwind.gen.js", // generated by scripts/gen-tw.mjs
    "storybook/storybook-static/**",
    "storybook/node_modules/**",
    "bun.lock",
  ]),

  // --- src/** : browser web components (Lit) ---
  {
    files: ["src/**/*.js"],
    extends: [
      js.configs.recommended,
      lit.configs["flat/recommended"],
      wc.configs["flat/recommended"],
    ],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...globals.browser },
    },
    plugins: { import: importPlugin, "check-file": checkFile, jsdoc },
    // No jsconfig/tsconfig here — the node resolver resolves the bare `lit`
    // dependency and the explicit-`.js` relative imports the browser ESM needs.
    settings: { "import/resolver": { node: { extensions: [".js", ".json"] } } },
    rules: {
      ...airbnb,
      "no-empty": ["error", { allowEmptyCatch: true }],
      // Require a JSDoc block on the public surface — exported functions/classes and
      // public (non-`_`) methods incl. the HA card-contract statics. Private `_`
      // helpers and inline arrows stay documented by their `//` WHY-comments.
      "jsdoc/require-jsdoc": [
        "error",
        {
          // Disable the built-in defaults (which would demand JSDoc on every
          // FunctionDeclaration, including non-exported module helpers) and require
          // it only on the explicit public surface below.
          require: {
            FunctionDeclaration: false,
            ArrowFunctionExpression: false,
            FunctionExpression: false,
            ClassDeclaration: false,
            MethodDefinition: false,
          },
          contexts: [
            "ExportNamedDeclaration > FunctionDeclaration",
            "ExportNamedDeclaration > VariableDeclaration > VariableDeclarator > ArrowFunctionExpression",
            "ExportNamedDeclaration > ClassDeclaration",
            "MethodDefinition[key.name!=/^_/]",
          ],
          checkConstructors: false,
        },
      ],
      "jsdoc/require-description": "error",
      "import/no-unresolved": "error",
      "import/order": [
        "warn",
        {
          groups: [
            "builtin",
            "external",
            "internal",
            "parent",
            "sibling",
            "index",
          ],
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true },
        },
      ],
      "import/newline-after-import": ["warn", { count: 1 }],
      "import/no-extraneous-dependencies": ["warn", { devDependencies: false }],
      "check-file/filename-naming-convention": [
        "error",
        { "**/*.js": "KEBAB_CASE" },
        { ignoreMiddleExtensions: true },
      ],
    },
  },

  // --- build scripts + this config : Node ---
  {
    files: ["scripts/**/*.mjs", "eslint.config.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...globals.node },
    },
    rules: {
      "no-var": "error",
      "prefer-const": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
    },
  },

  // --- storybook : browser stories + Node config, its own deps + file naming ---
  {
    files: ["storybook/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: { import: importPlugin },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "import/no-extraneous-dependencies": "off",
    },
  },

  // Disables stylistic rules that would fight Prettier — must stay last.
  prettier,
]);
