/**
 * gen-icons.mjs — inline the whole Solar Bold Duotone style into src/icons.gen.js.
 *
 * Pulls every `*-bold-duotone` icon body from @iconify-json/solar (a devDependency)
 * and writes a committed registry keyed `solar:<name>`. Run with: `bun run gen-icons`.
 * No network at runtime — this is build-time only.
 *
 * We ship the entire bold-duotone style (~1,325 icons) so that any
 * `solar:<name>-bold-duotone` a user puts in their dashboard renders on a HACS
 * install without a rebuild. `<fib-icon>` resolves names from this registry; other
 * styles (`-linear`, …) and typos fall through to its warn + placeholder.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const solar = JSON.parse(
  readFileSync(
    join(root, "node_modules/@iconify-json/solar/icons.json"),
    "utf8",
  ),
);

const defW = solar.width || 24;
const defH = solar.height || 24;

const names = Object.keys(solar.icons)
  .filter((name) => name.endsWith("-bold-duotone"))
  .sort();

const out = {};
for (const name of names) {
  const icon = solar.icons[name];
  const w = icon.width || defW;
  const h = icon.height || defH;
  out["solar:" + name] = { body: icon.body, vb: `0 0 ${w} ${h}` };
}

const header = `/* GENERATED by scripts/gen-icons.mjs from @iconify-json/solar — do not edit.
 * The full Solar Bold Duotone style is shipped. Re-generate with: bun run gen-icons */\n`;
const body = `export const ICONS = ${JSON.stringify(out, null, 2)};\n`;
writeFileSync(join(root, "src/icons.gen.js"), header + body);

console.log(
  `gen-icons: wrote ${Object.keys(out).length} icons to src/icons.gen.js`,
);
