/**
 * gen-icons.mjs — split the Solar Bold Duotone set into an eager core and a lazy
 * full set.
 *
 *   src/generated/icons.core.gen.js  — only the `solar:` names referenced in src/ (+ stories),
 *                            statically imported by icon.js. Keeps the bundle small.
 *   dist/icons.full.json   — the whole ~1325-icon Bold Duotone style, shipped next
 *                            to fibbers.js and fetched once, on demand, the first
 *                            time a card names an icon that isn't in the core.
 *
 * The full style stays reachable so any YAML config can still name any Solar icon —
 * just not eagerly (it was 91% of the bundle). Build-time only; run: `bun run
 * gen-icons`.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const solar = JSON.parse(
  readFileSync(
    join(root, "node_modules/@iconify-json/solar/icons.json"),
    "utf8",
  ),
);

const defW = solar.width || 24;
const defH = solar.height || 24;

// The whole Bold Duotone style → the full map (sorted for a stable diff).
const full = {};
for (const name of Object.keys(solar.icons)
  .filter((name) => name.endsWith("-bold-duotone"))
  .sort()) {
  const icon = solar.icons[name];
  full[`solar:${name}`] = {
    body: icon.body,
    vb: `0 0 ${icon.width || defW} ${icon.height || defH}`,
  };
}

// Which `solar:` names does the code actually reference? Scan the same roots the
// icon guard checks, so core is exactly what ships statically.
const roots = [join(root, "src"), join(root, "storybook/stories")];
const skip = join(root, "src/generated/icons.core.gen.js");
const re = /solar:[a-z0-9-]+/g;

function sourceFiles(dir) {
  const out = [];
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return out; // a root that doesn't exist (e.g. no storybook) is fine
  }
  for (const entry of entries) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) out.push(...sourceFiles(p));
    else if ((p.endsWith(".ts") || p.endsWith(".js")) && p !== skip)
      out.push(p);
  }
  return out;
}

const referenced = new Set();
for (const base of roots)
  for (const file of sourceFiles(base))
    for (const name of readFileSync(file, "utf8").match(re) || [])
      referenced.add(name);

const core = {};
for (const name of [...referenced].sort())
  if (full[name]) core[name] = full[name];

writeFileSync(
  join(root, "src/generated/icons.core.gen.js"),
  `/* GENERATED by scripts/gen-icons.mjs — do not edit. The core set: only the Solar
 * icons referenced in src/. Any other \`solar:\` name is fetched from
 * dist/icons.full.json on demand (see icon.js). Re-generate: bun run gen-icons */
export const ICONS = ${JSON.stringify(core, null, 2)};
`,
);

// The full set as a plain JSON asset, shipped alongside fibbers.js.
writeFileSync(
  join(root, "dist/icons.full.json"),
  `${JSON.stringify(full)}\n`,
);

console.log(
  `gen-icons: core ${Object.keys(core).length} → src/generated/icons.core.gen.js, ` +
    `full ${Object.keys(full).length} → dist/icons.full.json`,
);
